replicaCount: 2

image:
  repository: ghcr.io/kcearns/k8s-express-test/k8s-express-test
  tag: 2f5d687
  pullPolicy: IfNotPresent

service:
  name: k8s-express-test-service
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  name: dev